# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rinfa_wrappers", use_symbols = TRUE, package_name = "rinfa")

#' @usage NULL
#' @useDynLib rinfa, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
fit_linear_reg_linfa <- function() .Call(wrap__fit_linear_reg_linfa)

#' @export
predict_linear_reg_linfa <- function(model) .Call(wrap__predict_linear_reg_linfa, model)


# nolint end
