# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rinfa_wrappers", use_symbols = TRUE, package_name = "rinfa")

#' @usage NULL
#' @useDynLib rinfa, .registration = TRUE
NULL

fit_naive_Bayes <- function(x, y, var_smoothing) .Call(wrap__fit_naive_Bayes, x, y, var_smoothing)

predict_naive_Bayes <- function(model, x) .Call(wrap__predict_naive_Bayes, model, x)

fit_linear_reg <- function(x, y) .Call(wrap__fit_linear_reg, x, y)

predict_linear_reg <- function(model, x) .Call(wrap__predict_linear_reg, model, x)

fit_logistic_reg <- function(x, y) .Call(wrap__fit_logistic_reg, x, y)

predict_logistic_reg <- function(model, x) .Call(wrap__predict_logistic_reg, model, x)

fit_multinom_reg <- function(x, y, n_features) .Call(wrap__fit_multinom_reg, x, y, n_features)

predict_multinom_reg <- function(model, x, n_features) .Call(wrap__predict_multinom_reg, model, x, n_features)

fit_svm_linear <- function(x, y, n_features, c) .Call(wrap__fit_svm_linear, x, y, n_features, c)

predict_svm_linear <- function(model, x, n_features) .Call(wrap__predict_svm_linear, model, x, n_features)

fit_decision_tree <- function(x, y, n_features, min_impurity_decrease, max_depth, min_weight_split) .Call(wrap__fit_decision_tree, x, y, n_features, min_impurity_decrease, max_depth, min_weight_split)

predict_decision_tree <- function(model, x, n_features) .Call(wrap__predict_decision_tree, model, x, n_features)


# nolint end
